"""Creating correct table

Revision ID: 32e56e27306c
Revises: 26dfabcee9ba
Create Date: 2023-03-05 14:22:04.848439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e56e27306c'
down_revision = '26dfabcee9ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
