"""creating products table

Revision ID: 7556de7bb1c6
Revises: 6aabede72bba
Create Date: 2023-03-13 20:31:39.449316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7556de7bb1c6'
down_revision = '6aabede72bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='stats_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stats_pkey')
    )
    # ### end Alembic commands ###
