"""Creating tables products and stats

Revision ID: 86e3c10f44db
Revises: 08cf5c223ccd
Create Date: 2023-03-05 11:37:56.269981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e3c10f44db'
down_revision = '08cf5c223ccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priduct_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('price', sa.Numeric(precision=2, scale=7), nullable=False),
    sa.ForeignKeyConstraint(['priduct_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('product')
    # ### end Alembic commands ###
